<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="44902" started-at="2020-08-18T04:11:04Z" finished-at="2020-08-18T04:11:49Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="44902" started-at="2020-08-18T04:11:04Z" finished-at="2020-08-18T04:11:49Z">
      <class name="p1.DataDrv">
        <test-method status="PASS" signature="f(java.lang.String, java.lang.String)[pri:0, instance:p1.DataDrv@5d5eef3d]" name="f" duration-ms="18895" started-at="2020-08-18T04:11:04Z" data-provider="LoginCredentials" finished-at="2020-08-18T04:11:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[edward]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qwerty123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:p1.DataDrv@5d5eef3d]" name="tearDown" is-config="true" duration-ms="4756" started-at="2020-08-18T04:11:23Z" finished-at="2020-08-18T04:11:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="f(java.lang.String, java.lang.String)[pri:0, instance:p1.DataDrv@5d5eef3d]" name="f" duration-ms="15991" started-at="2020-08-18T04:11:28Z" data-provider="LoginCredentials" finished-at="2020-08-18T04:11:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[9885353910]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Virat910]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[user is not able to access-invalid credentials expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: user is not able to access-invalid credentials expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at p1.DataDrv.f(DataDrv.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:p1.DataDrv@5d5eef3d]" name="tearDown" is-config="true" duration-ms="5189" started-at="2020-08-18T04:11:44Z" finished-at="2020-08-18T04:11:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- p1.DataDrv -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
